export const uploaded_resume_url = 'https://s3-us-west-2.amazonaws.com/resume-gen/resume.pdf'
export const resume_bucket_url = 'https://s3-us-west-2.amazonaws.com/resume-gen/resumes'
// export const server_url = 'http://csresu.me/api'
export const server_url = 'http://127.0.0.1:5000/api'
export const current_version = '1.0'
